# Copyright 2020 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/toolchain/win/midl.gni")
import("//chrome/updater/branding.gni")
import("//chrome/version.gni")

# These GUIDs must depend on branding only.
branding_only_placeholder_guids = [
  "PLACEHOLDER-GUID-35db72c7-3d9f-4d0f-a43b-97e555457cee",  # UpdaterLib

  "PLACEHOLDER-GUID-c8cfd284-3060-4975-80f0-90c5248558c4",  # UpdaterUserClass
  "PLACEHOLDER-GUID-b2f0fe85-36a7-4a99-a586-70beb7a07a56",  # UpdaterSystemClass

  "PLACEHOLDER-GUID-1db3ab34-5dac-4e4d-b52f-8e477229b246",  # IUpdater
  "PLACEHOLDER-GUID-3371de54-71bc-4731-8a57-aa2e4228c488",  # IUpdaterUser
  "PLACEHOLDER-GUID-36bcf03a-0c27-413d-b7c4-74019be82182",  # IUpdaterSystem

  "PLACEHOLDER-GUID-9b510a0d-70d5-40da-a981-d260d84ef01a",  # IUpdateState
  "PLACEHOLDER-GUID-9333a95a-6e3c-458d-9ce4-d067bb162e77",  # IUpdateStateUser
  "PLACEHOLDER-GUID-7c21013c-5100-4199-a42f-f0d2b8600881",  # IUpdateStateSystem

  "PLACEHOLDER-GUID-8b49de49-110b-4cdd-9412-39c86322e0b7",  # ICompleteStatus
  "PLACEHOLDER-GUID-d92e1cb4-3ed8-4a02-9677-e221c94f14cd",  # ICompleteStatusUser
  "PLACEHOLDER-GUID-c08e5c24-89ed-4817-94a5-cdd88a8209d6",  # ICompleteStatusSystem

  "PLACEHOLDER-GUID-1a03d10f-afd0-43bc-8c85-d56de52ceb86",  # IUpdaterObserver
  "PLACEHOLDER-GUID-cd709ed0-ea6c-4ece-8932-14dca609aa96",  # IUpdaterObserverUser
  "PLACEHOLDER-GUID-1b5513f0-7548-478e-9fc3-2c756bb71103",  # IUpdaterObserverSystem

  "PLACEHOLDER-GUID-839e2896-d896-479f-b480-8b5d64ccf30d",  # IUpdaterCallback
  "PLACEHOLDER-GUID-7e3e3c4c-8050-4175-bfaf-136010984395",  # IUpdaterCallbackUser
  "PLACEHOLDER-GUID-90b6f617-7cbb-4eef-95a9-94db1106c29c",  # IUpdaterCallbackSystem
]

uuid5_guids = []
foreach(guid, branding_only_placeholder_guids) {
  uuid5_guids += [ guid + "=uuid5:$updater_product_full_name" ]
}
uuid5_guids = string_join(",", uuid5_guids)

midl("updater_idl_idl") {
  dynamic_guids = "ignore_proxy_stub," + uuid5_guids

  sources = [ "updater_idl.template" ]

  writes_tlb = true
}

# These GUIDs must depend on branding and version.
branding_version_placeholder_guids = [
  "PLACEHOLDER-GUID-12778e38-dc6c-4d53-bcba-b78ffe2d25cf",  # UpdaterInternalLib
  "PLACEHOLDER-GUID-2e437ffb-f921-47a1-a4de-ae318b9411f4",  # UpdaterInternalUserClass
  "PLACEHOLDER-GUID-1bac6195-2f6d-4fe3-bf1e-49bf035f20de",  # UpdaterInternalSystemClass
  "PLACEHOLDER-GUID-4fe3d8ec-22b7-4a89-ae39-5ec29fdf244e",  # IUpdaterInternal
  "PLACEHOLDER-GUID-1d39542f-c795-4f38-a8f7-456029f5949b",  # IUpdaterInternalUser
  "PLACEHOLDER-GUID-48b004e4-f8c1-4672-b435-e3339c05d40a",  # IUpdaterInternalSystem
  "PLACEHOLDER-GUID-e06e0716-c0e6-4c67-b8d6-cf9beabd150b",  # IUpdaterInternalCallback
  "PLACEHOLDER-GUID-d078d752-39d7-4829-92e9-27611b68055f",  # IUpdaterInternalCallbackUser
  "PLACEHOLDER-GUID-4b0bc642-93fc-417e-be91-4b5e8dbf4279",  # IUpdaterInternalCallbackSystem
]

uuid5_guids = []
foreach(guid, branding_version_placeholder_guids) {
  uuid5_guids +=
      [ guid + "=uuid5:$updater_product_full_name$chrome_version_full" ]
}
uuid5_guids = string_join(",", uuid5_guids)

midl("updater_internal_idl_idl") {
  dynamic_guids = "ignore_proxy_stub," + uuid5_guids

  sources = [ "updater_internal_idl.template" ]

  writes_tlb = true
}

updater_legacy_idl_guids = []
if (is_chrome_branded) {
  # Google-specific Legacy GUIDs that Omaha 4 supports.
  updater_legacy_idl_guids = [
    "PLACEHOLDER-GUID-c8a4e4b7-c77c-43a2-bb47-4327108efeb3=35db72c7-3d9f-4d0f-a43b-97e555457cee",  # UpdaterLegacyLib
    "PLACEHOLDER-GUID-49c22599-8b94-4a16-aebd-23f533adc662=d3acb180-3f43-40c7-b377-df76f06f08e6",  # GoogleUpdate3WebUserClass
    "PLACEHOLDER-GUID-5ccebfac-038e-48bc-bd17-1e4cd31aedcc=3c8e80fb-25ef-4bd5-a6a5-f18b8b71c6cd",  # GoogleUpdate3WebSystemClass
    "PLACEHOLDER-GUID-aa02ac30-a261-47ec-bff3-051be8d48042=fdd502ea-8d9b-49c4-ac16-5adc88f61e8f",  # GoogleUpdate3WebServiceClass
    "PLACEHOLDER-GUID-b6dd0fb6-83e1-467d-a41d-db413853110b=2830df33-9cd4-44b7-ad81-0df3b1b07108",  # PolicyStatusUserClass
    "PLACEHOLDER-GUID-5945f6c3-7a87-4185-9d4d-3ed5e5541565=874ea82f-0434-48de-8248-54a403873c76",  # PolicyStatusSystemClass
    "PLACEHOLDER-GUID-327e0927-095d-4e0e-9901-7dc16a740034=bb407617-cd01-4649-9660-ad011c9735f5",  # ProcessLauncherClass
    "PLACEHOLDER-GUID-707777da-3324-4a54-90b0-f94f917f51a5=5b03e20c-d3ac-4d20-a348-f28ad09036d3",  # ICurrentState
    "PLACEHOLDER-GUID-1756e258-c4a1-4123-9027-736769e118a6=61c1a1af-bc2a-460f-9c25-f1ee7c691646",  # IGoogleUpdate3Web
    "PLACEHOLDER-GUID-b0b5a77b-0ccb-4539-a365-9d36712406c8=2d0728e9-be51-4d6e-8f6c-70074f36f8b7",  # IAppBundleWeb
    "PLACEHOLDER-GUID-c061d8c1-6294-414a-969c-c21a18b382f8=3b7b2380-9bc0-4980-80ca-f90bc5a27e02",  # IAppWeb
    "PLACEHOLDER-GUID-8359752c-37fb-4255-896b-5acf376ee108=871fb7ee-e700-478e-945a-a368fd7f9a1a",  # IAppCommandWeb
    "PLACEHOLDER-GUID-30eb08d2-4c42-4436-9592-4b64a238d8c7=870a7690-7ee5-4b66-aec2-aee65eb1d9cc",  # IPolicyStatus
    "PLACEHOLDER-GUID-25b52d13-58b5-4a85-aa25-0cd08f8fa8c4=5601ad70-a5ae-4438-b0b9-7bc8b330812a",  # IPolicyStatus2
    "PLACEHOLDER-GUID-7b39f599-872e-42dc-a409-768bc207cee0=d7807220-76c1-4c96-a6d1-577c4a8dbe31",  # IPolicyStatus3
    "PLACEHOLDER-GUID-42b8a4ae-1e7f-47a0-b39e-2ea627c2a9d0=8ff73970-4955-4a73-9cb8-de8924a8c83a",  # IPolicyStatusValue
    "PLACEHOLDER-GUID-ee9e682f-9b43-4ce1-b298-91efe68a825d=0c0e0fa4-09c0-4eb0-ac8c-6e3701f4a3c3",  # IProcessLauncher
    "PLACEHOLDER-GUID-a55bc9c5-b6cb-41f1-a6fc-03afc53bff85=223dd50e-335a-41d0-b66f-5a4de520aefe",  # IProcessLauncher2s
  ]
} else {
  updater_legacy_idl_guids = [
    "PLACEHOLDER-GUID-c8a4e4b7-c77c-43a2-bb47-4327108efeb3=35db72c7-3d9f-4d0f-a43b-97e555457cee",  # UpdaterLegacyLib
    "PLACEHOLDER-GUID-49c22599-8b94-4a16-aebd-23f533adc662=d3acb180-3f43-40c7-b377-df76f06f08e6",  # GoogleUpdate3WebUserClass
    "PLACEHOLDER-GUID-5ccebfac-038e-48bc-bd17-1e4cd31aedcc=3c8e80fb-25ef-4bd5-a6a5-f18b8b71c6cd",  # GoogleUpdate3WebSystemClass
    "PLACEHOLDER-GUID-aa02ac30-a261-47ec-bff3-051be8d48042=fdd502ea-8d9b-49c4-ac16-5adc88f61e8f",  # GoogleUpdate3WebServiceClass
    "PLACEHOLDER-GUID-b6dd0fb6-83e1-467d-a41d-db413853110b=2830df33-9cd4-44b7-ad81-0df3b1b07108",  # PolicyStatusUserClass
    "PLACEHOLDER-GUID-5945f6c3-7a87-4185-9d4d-3ed5e5541565=874ea82f-0434-48de-8248-54a403873c76",  # PolicyStatusSystemClass
    "PLACEHOLDER-GUID-327e0927-095d-4e0e-9901-7dc16a740034=bb407617-cd01-4649-9660-ad011c9735f5",  # ProcessLauncherClass
    "PLACEHOLDER-GUID-707777da-3324-4a54-90b0-f94f917f51a5=5b03e20c-d3ac-4d20-a348-f28ad09036d3",  # ICurrentState
    "PLACEHOLDER-GUID-1756e258-c4a1-4123-9027-736769e118a6=61c1a1af-bc2a-460f-9c25-f1ee7c691646",  # IGoogleUpdate3Web
    "PLACEHOLDER-GUID-b0b5a77b-0ccb-4539-a365-9d36712406c8=2d0728e9-be51-4d6e-8f6c-70074f36f8b7",  # IAppBundleWeb
    "PLACEHOLDER-GUID-c061d8c1-6294-414a-969c-c21a18b382f8=3b7b2380-9bc0-4980-80ca-f90bc5a27e02",  # IAppWeb
    "PLACEHOLDER-GUID-8359752c-37fb-4255-896b-5acf376ee108=871fb7ee-e700-478e-945a-a368fd7f9a1a",  # IAppCommandWeb
    "PLACEHOLDER-GUID-30eb08d2-4c42-4436-9592-4b64a238d8c7=870a7690-7ee5-4b66-aec2-aee65eb1d9cc",  # IPolicyStatus
    "PLACEHOLDER-GUID-25b52d13-58b5-4a85-aa25-0cd08f8fa8c4=5601ad70-a5ae-4438-b0b9-7bc8b330812a",  # IPolicyStatus2
    "PLACEHOLDER-GUID-7b39f599-872e-42dc-a409-768bc207cee0=d7807220-76c1-4c96-a6d1-577c4a8dbe31",  # IPolicyStatus3
    "PLACEHOLDER-GUID-42b8a4ae-1e7f-47a0-b39e-2ea627c2a9d0=8ff73970-4955-4a73-9cb8-de8924a8c83a",  # IPolicyStatusValue
    "PLACEHOLDER-GUID-ee9e682f-9b43-4ce1-b298-91efe68a825d=0c0e0fa4-09c0-4eb0-ac8c-6e3701f4a3c3",  # IProcessLauncher
    "PLACEHOLDER-GUID-a55bc9c5-b6cb-41f1-a6fc-03afc53bff85=223dd50e-335a-41d0-b66f-5a4de520aefe",  # IProcessLauncher2
  ]
}
updater_legacy_idl_guids = string_join(",", updater_legacy_idl_guids)

midl("updater_legacy_idl_idl") {
  dynamic_guids = "ignore_proxy_stub," + updater_legacy_idl_guids

  sources = [ "updater_legacy_idl.template" ]
  writes_tlb = true
}

# The COM server needs to work with Windows 7, so explicitly setting the defines
# to reflect this. Otherwise, WRL uses APIs that are only available in later
# Windows versions.
config("winver") {
  defines = [
    "NTDDI_VERSION=NTDDI_WIN7",

    # Hardcoding version 0x0601, since _WIN32_WINNT_WIN7 may not be defined.
    "_WIN32_WINNT=0x0601",
    "WINVER=0x0601",
  ]
}
