# Copyright 2020 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/toolchain/win/midl.gni")
import("//chrome/updater/branding.gni")
import("//chrome/version.gni")

# Processes IDL template files into a new IDL template with distinct user and
# system identities for interfaces that are decorated with `BEGIN_INTERFACE` and
# `END_INTERFACE`.
template("generate_user_system_idl") {
  assert(defined(invoker.idl_template_filename),
         "Need `idl_template_filename` in $target_name.")

  action(target_name) {
    script = "generate_user_system_idl.py"
    inputs = [
      script,
      invoker.idl_template_filename,
    ]

    idl_filename = invoker.idl_template_filename
    if (invoker.generate_for != "") {
      idl_filename = get_path_info(invoker.idl_template_filename, "name") +
                     "_" + invoker.generate_for + "." +
                     get_path_info(invoker.idl_template_filename, "extension")
    }

    output_file = "${target_gen_dir}/${idl_filename}"
    args = [
      "--idl_template_file",
      rebase_path(invoker.idl_template_filename, root_build_dir),
      "--idl_output_file",
      rebase_path(output_file, root_build_dir),
    ]
    if (invoker.generate_for != "") {
      args += [
        "--generate_for",
        invoker.generate_for,
      ]
    }
    outputs = [ output_file ]
  }
}

template("midl_user_system_idl") {
  assert(defined(invoker.replacement_guids),
         "Need `replacement_guids` in $target_name for placeholder guids.")

  foreach(scope,
          [
            "",
            "user",
            "system",
          ]) {
    midl_target_name = target_name
    if (scope != "") {
      midl_target_name = target_name + "_" + scope
    }
    target_name_generate = midl_target_name + "_gen"
    target_name_template = target_name + ".template"

    generate_user_system_idl(target_name_generate) {
      idl_template_filename = target_name_template
      generate_for = scope
    }

    midl(midl_target_name) {
      dynamic_guids = "ignore_proxy_stub," + invoker.replacement_guids
      sources = get_target_outputs(":$target_name_generate")
      writes_tlb = true
      deps = [ ":$target_name_generate" ]
    }
  }
}

# These GUIDs must depend on branding only.
branding_only_placeholder_guids = [
  "PLACEHOLDER-GUID-8b10c18e-130b-49ec-a615-6dae002ef7fa",  # UpdaterLib

  "PLACEHOLDER-GUID-b08f92a7-0f66-4788-ade2-12e3ee767337",  # UpdaterUserClass
  "PLACEHOLDER-GUID-9efa113e-960e-415d-9368-8111cf6887a4",  # UpdaterSystemClass

  "PLACEHOLDER-GUID-e4978a53-2b98-415b-9cd9-5f8ffcf2cd8d",  # IUpdater
  "PLACEHOLDER-GUID-4808f7ec-9328-460c-bf5c-205f535d9083",  # IUpdaterUser
  "PLACEHOLDER-GUID-f3b9c0b6-f616-4594-8d2b-cb94ce5d0609",  # IUpdaterSystem

  "PLACEHOLDER-GUID-561c4cda-67b4-4f07-8034-57686c169a85",  # IUpdateState
  "PLACEHOLDER-GUID-05a0ad46-45f4-4418-ae74-5d02a8d589fb",  # IUpdateStateUser
  "PLACEHOLDER-GUID-3a4af098-4de8-4b08-9f7b-1f448672ff57",  # IUpdateStateSystem

  "PLACEHOLDER-GUID-05e1af35-4049-4e5f-899d-a5d2a2004584",  # ICompleteStatus
  "PLACEHOLDER-GUID-4c51462d-633c-4aba-8992-f6aa96be2811",  # ICompleteStatusUser
  "PLACEHOLDER-GUID-6e558213-32b7-43aa-b264-b43742b89775",  # ICompleteStatusSystem

  "PLACEHOLDER-GUID-b821c062-7b0d-4752-bd8c-09a57482d354",  # IUpdaterObserver
  "PLACEHOLDER-GUID-c8f78e13-fc5e-4d6b-aa77-4d5ba9814a5a",  # IUpdaterObserverUser
  "PLACEHOLDER-GUID-ba95a33a-f4af-42cc-817a-c1af234cda6f",  # IUpdaterObserverSystem

  "PLACEHOLDER-GUID-fc220576-3e97-482c-89ad-3df31fcf9bce",  # IUpdaterCallback
  "PLACEHOLDER-GUID-213bcdb7-f6e5-4852-852b-2a3daed80125",  # IUpdaterCallbackUser
  "PLACEHOLDER-GUID-3a3c8f26-bad0-40ad-8dd9-e25377552d65",  # IUpdaterCallbackSystem

  "PLACEHOLDER-GUID-A22AFC54-2DEF-4578-9187-DB3B24381090",  # IUpdaterAppState
  "PLACEHOLDER-GUID-028FEB84-44BC-4A73-A0CD-603678155CC3",  # IUpdaterAppStateUser
  "PLACEHOLDER-GUID-92631531-8044-46F4-B645-CDFBCCC7FA3B",  # IUpdaterAppStateSystem

  "PLACEHOLDER-GUID-EFE903C0-E820-4136-9FAE-FDCD7F256302",  # IUpdaterAppStatesCallback
  "PLACEHOLDER-GUID-BCFCF95C-DE48-4F42-B0E9-D50DB407DB53",  # IUpdaterAppStatesCallbackUser
  "PLACEHOLDER-GUID-2CB8867E-495E-459F-B1B6-2DD7FFDBD462",  # IUpdaterAppStatesCallbackSystem
]

uuid5_guids = []
foreach(guid, branding_only_placeholder_guids) {
  uuid5_guids += [ guid + "=uuid5:$updater_product_full_name" ]
}
uuid5_guids = string_join(",", uuid5_guids)

midl_user_system_idl("updater_idl") {
  replacement_guids = uuid5_guids
}

# These GUIDs must depend on branding and version.
branding_version_placeholder_guids = [
  "PLACEHOLDER-GUID-bf6a517f-a55f-4a24-ae4b-225c075966c5",  # UpdaterInternalLib
  "PLACEHOLDER-GUID-e4d1bba3-9ea7-4d40-8e71-4be4d7bfc633",  # UpdaterInternalUserClass
  "PLACEHOLDER-GUID-ebe1e420-afaf-471b-812c-3241e55630f9",  # UpdaterInternalSystemClass
  "PLACEHOLDER-GUID-1947672a-e51d-4d50-bf1d-f32d850b94c1",  # IUpdaterInternal
  "PLACEHOLDER-GUID-cc5ed350-079e-4789-91d4-f83ce0c87bce",  # IUpdaterInternalUser
  "PLACEHOLDER-GUID-72a5f0a6-f5de-4fc0-8f46-ae4eb9649307",  # IUpdaterInternalSystem
  "PLACEHOLDER-GUID-894794fb-535e-4b6b-8d00-e58f41a72c95",  # IUpdaterInternalCallback
  "PLACEHOLDER-GUID-c4f09781-044f-4870-9ba6-b72ba627dc3a",  # IUpdaterInternalCallbackUser
  "PLACEHOLDER-GUID-73209e3a-80b6-44dd-98a6-e72bd4bae9ac",  # IUpdaterInternalCallbackSystem
]

uuid5_guids = []
foreach(guid, branding_version_placeholder_guids) {
  uuid5_guids +=
      [ guid + "=uuid5:$updater_product_full_name$chrome_version_full" ]
}
uuid5_guids = string_join(",", uuid5_guids)

midl_user_system_idl("updater_internal_idl") {
  replacement_guids = uuid5_guids
}

updater_legacy_idl_guids = [
  "PLACEHOLDER-GUID-d789bec4-f247-42df-ad56-fa5775b61848=$UpdaterLegacyLibGUID",
  "PLACEHOLDER-GUID-03f6780a-31ee-45f0-b55e-f0d465d8bb3a=$GoogleUpdate3WebUserClassGUID",
  "PLACEHOLDER-GUID-f4bb2727-3a47-479c-a0b8-7c3ee73cddf7=$GoogleUpdate3WebSystemClassGUID",
  "PLACEHOLDER-GUID-568a8900-e3db-4fa0-b320-5ead284038c6=$GoogleUpdate3WebServiceClassGUID",
  "PLACEHOLDER-GUID-d48c091a-dea9-41e4-9d36-5ad849a466c5=$PolicyStatusUserClassGUID",
  "PLACEHOLDER-GUID-58712509-616f-40c5-9682-427c15432c4c=$PolicyStatusSystemClassGUID",
  "PLACEHOLDER-GUID-163b3ca0-8d0b-47ca-817d-41c638fa9260=$ProcessLauncherClassGUID",

  "PLACEHOLDER-GUID-AA10D17D-7A09-48AC-B1E4-F124937E3D26=$IAppVersionWebGUID",
  "PLACEHOLDER-GUID-AC817E10-993C-470F-8DCA-25F53D70EA8D=$IAppVersionWebUserGUID",
  "PLACEHOLDER-GUID-9367601E-C100-4702-8755-808D6BB385D8=$IAppVersionWebSystemGUID",

  "PLACEHOLDER-GUID-87a931b9-770b-4403-a1eb-a8e8f8cb1892=$ICurrentStateGUID",
  "PLACEHOLDER-GUID-31479718-D170-467B-9274-27FC3E88CB76=$ICurrentStateUserGUID",
  "PLACEHOLDER-GUID-71CBC6BB-CA4B-4B5A-83C0-FC95F9CA6A30=$ICurrentStateSystemGUID",

  "PLACEHOLDER-GUID-0b0d10c8-d604-406d-96f7-21fe78212c50=$IGoogleUpdate3WebGUID",
  "PLACEHOLDER-GUID-EE8EE731-C592-4A4F-9774-BB04337B8F46=$IGoogleUpdate3WebUserGUID",
  "PLACEHOLDER-GUID-AE5F8C9D-B94D-4367-A422-D1DC4E913A52=$IGoogleUpdate3WebSystemGUID",

  "PLACEHOLDER-GUID-3c027e5a-adc6-4d87-93b8-36596b50a845=$IAppBundleWebGUID",
  "PLACEHOLDER-GUID-CE7A37FD-A255-460C-BAF1-708765EB76EC=$IAppBundleWebUserGUID",
  "PLACEHOLDER-GUID-BFFD766D-A2DD-436E-89FA-BF05BC5B5958=$IAppBundleWebSystemGUID",

  "PLACEHOLDER-GUID-fc0f00b9-36a6-47c1-aa51-a3dcbab09c01=$IAppWebGUID",
  "PLACEHOLDER-GUID-47B9D508-CB72-4F8B-AF00-7D0143603B25=$IAppWebUserGUID",
  "PLACEHOLDER-GUID-540B227A-F442-45D5-BA52-298A05BAF1A8=$IAppWebSystemGUID",

  "PLACEHOLDER-GUID-87a649eb-2cc7-46c3-82ea-b674f568b2a4=$IAppCommandWebGUID",
  "PLACEHOLDER-GUID-5515E66F-FA6F-4D74-B5EA-4FCFDA16FE12=$IAppCommandWebUserGUID",
  "PLACEHOLDER-GUID-C6E2C5D5-86FA-4A64-9D08-8C9B644F0E49=$IAppCommandWebSystemGUID",

  "PLACEHOLDER-GUID-973209b4-6d14-4865-9716-905aee40ebe4=$IPolicyStatusGUID",
  "PLACEHOLDER-GUID-EF739C0C-40B0-478D-B76B-3659B8F2B0EB=$IPolicyStatusUserGUID",
  "PLACEHOLDER-GUID-F3964464-A939-44D3-9244-36BD2E3630B8=$IPolicyStatusSystemGUID",

  "PLACEHOLDER-GUID-b591952e-3ef9-4d50-bf39-ef3e79960430=$IPolicyStatus2GUID",
  "PLACEHOLDER-GUID-AD91C851-86AC-499F-9BA9-9A561744AA4D=$IPolicyStatus2UserGUID",
  "PLACEHOLDER-GUID-F4A0362A-3702-48B8-9896-7D8013D03AB2=$IPolicyStatus2SystemGUID",

  "PLACEHOLDER-GUID-778267d6-1b65-4170-ae79-9056dd3a013b=$IPolicyStatus3GUID",
  "PLACEHOLDER-GUID-BC39E1E1-E8FA-4E72-903F-3BF346E7E165=$IPolicyStatus3UserGUID",
  "PLACEHOLDER-GUID-7B26CC23-B2B8-441B-AA9C-8B551ABB611B=$IPolicyStatus3SystemGUID",

  "PLACEHOLDER-GUID-C07BC046-32E0-4184-BC9F-13C4533C24AC=$IPolicyStatus4GUID",
  "PLACEHOLDER-GUID-0F6696F3-7F48-446B-97FA-6B34EC2ADB32=$IPolicyStatus4UserGUID",
  "PLACEHOLDER-GUID-423FDEC3-0DBC-441E-B51D-FD8B82B9DCF2=$IPolicyStatus4SystemGUID",

  "PLACEHOLDER-GUID-b5f81657-0809-4dbf-89ba-1e5fb6f28989=$IPolicyStatusValueGUID",
  "PLACEHOLDER-GUID-7E0A6B39-7CEB-4944-ABFA-F419D201D6A0=$IPolicyStatusValueUserGUID",
  "PLACEHOLDER-GUID-CC2CCD05-119C-44E1-852D-6DCC2DFB72EC=$IPolicyStatusValueSystemGUID",

  "PLACEHOLDER-GUID-97addc89-d368-4d88-8f01-cb69c402fbaf=$IProcessLauncherGUID",
  "PLACEHOLDER-GUID-FFBAEC45-C5EC-4287-85CD-A831796BE952=$IProcessLauncherSystemGUID",

  "PLACEHOLDER-GUID-76868039-4be2-40bf-bb96-a7644861eeff=$IProcessLauncher2GUID",
  "PLACEHOLDER-GUID-5F41DC50-029C-4F5A-9860-EF352A0B66D2=$IProcessLauncher2SystemGUID",
]
updater_legacy_idl_guids = string_join(",", updater_legacy_idl_guids)

midl_user_system_idl("updater_legacy_idl") {
  replacement_guids = updater_legacy_idl_guids
}

# The COM server needs to work with Windows 7, so explicitly setting the defines
# to reflect this. Otherwise, WRL uses APIs that are only available in later
# Windows versions.
config("winver") {
  defines = [
    "NTDDI_VERSION=NTDDI_WIN7",

    # Hardcoding version 0x0601, since _WIN32_WINNT_WIN7 may not be defined.
    "_WIN32_WINNT=0x0601",
    "WINVER=0x0601",
  ]
}
