# Copyright 2020 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/toolchain/win/midl.gni")
import("//chrome/updater/branding.gni")
import("//chrome/version.gni")

# These GUIDs must depend on branding only.
branding_only_placeholder_guids = [
  "PLACEHOLDER-GUID-cabd1cfd-2c5f-46a1-8105-564b3a6563ec",  # UpdaterLib

  "PLACEHOLDER-GUID-b08f92a7-0f66-4788-ade2-12e3ee767337",  # UpdaterUserClass
  "PLACEHOLDER-GUID-9efa113e-960e-415d-9368-8111cf6887a4",  # UpdaterSystemClass

  "PLACEHOLDER-GUID-e4978a53-2b98-415b-9cd9-5f8ffcf2cd8d",  # IUpdater
  "PLACEHOLDER-GUID-4808f7ec-9328-460c-bf5c-205f535d9083",  # IUpdaterUser
  "PLACEHOLDER-GUID-f3b9c0b6-f616-4594-8d2b-cb94ce5d0609",  # IUpdaterSystem

  "PLACEHOLDER-GUID-561c4cda-67b4-4f07-8034-57686c169a85",  # IUpdateState
  "PLACEHOLDER-GUID-05a0ad46-45f4-4418-ae74-5d02a8d589fb",  # IUpdateStateUser
  "PLACEHOLDER-GUID-3a4af098-4de8-4b08-9f7b-1f448672ff57",  # IUpdateStateSystem

  "PLACEHOLDER-GUID-05e1af35-4049-4e5f-899d-a5d2a2004584",  # ICompleteStatus
  "PLACEHOLDER-GUID-4c51462d-633c-4aba-8992-f6aa96be2811",  # ICompleteStatusUser
  "PLACEHOLDER-GUID-6e558213-32b7-43aa-b264-b43742b89775",  # ICompleteStatusSystem

  "PLACEHOLDER-GUID-b821c062-7b0d-4752-bd8c-09a57482d354",  # IUpdaterObserver
  "PLACEHOLDER-GUID-c8f78e13-fc5e-4d6b-aa77-4d5ba9814a5a",  # IUpdaterObserverUser
  "PLACEHOLDER-GUID-ba95a33a-f4af-42cc-817a-c1af234cda6f",  # IUpdaterObserverSystem

  "PLACEHOLDER-GUID-fc220576-3e97-482c-89ad-3df31fcf9bce",  # IUpdaterCallback
  "PLACEHOLDER-GUID-213bcdb7-f6e5-4852-852b-2a3daed80125",  # IUpdaterCallbackUser
  "PLACEHOLDER-GUID-3a3c8f26-bad0-40ad-8dd9-e25377552d65",  # IUpdaterCallbackSystem
]

uuid5_guids = []
foreach(guid, branding_only_placeholder_guids) {
  uuid5_guids += [ guid + "=uuid5:$updater_product_full_name" ]
}
uuid5_guids = string_join(",", uuid5_guids)

midl("updater_idl_idl") {
  dynamic_guids = "ignore_proxy_stub," + uuid5_guids

  sources = [ "updater_idl.template" ]

  writes_tlb = true
}

# These GUIDs must depend on branding and version.
branding_version_placeholder_guids = [
  "PLACEHOLDER-GUID-bf6a517f-a55f-4a24-ae4b-225c075966c5",  # UpdaterInternalLib
  "PLACEHOLDER-GUID-e4d1bba3-9ea7-4d40-8e71-4be4d7bfc633",  # UpdaterInternalUserClass
  "PLACEHOLDER-GUID-ebe1e420-afaf-471b-812c-3241e55630f9",  # UpdaterInternalSystemClass
  "PLACEHOLDER-GUID-1947672a-e51d-4d50-bf1d-f32d850b94c1",  # IUpdaterInternal
  "PLACEHOLDER-GUID-cc5ed350-079e-4789-91d4-f83ce0c87bce",  # IUpdaterInternalUser
  "PLACEHOLDER-GUID-72a5f0a6-f5de-4fc0-8f46-ae4eb9649307",  # IUpdaterInternalSystem
  "PLACEHOLDER-GUID-894794fb-535e-4b6b-8d00-e58f41a72c95",  # IUpdaterInternalCallback
  "PLACEHOLDER-GUID-c4f09781-044f-4870-9ba6-b72ba627dc3a",  # IUpdaterInternalCallbackUser
  "PLACEHOLDER-GUID-73209e3a-80b6-44dd-98a6-e72bd4bae9ac",  # IUpdaterInternalCallbackSystem
]

uuid5_guids = []
foreach(guid, branding_version_placeholder_guids) {
  uuid5_guids +=
      [ guid + "=uuid5:$updater_product_full_name$chrome_version_full" ]
}
uuid5_guids = string_join(",", uuid5_guids)

midl("updater_internal_idl_idl") {
  dynamic_guids = "ignore_proxy_stub," + uuid5_guids

  sources = [ "updater_internal_idl.template" ]

  writes_tlb = true
}

updater_legacy_idl_guids = []
if (is_chrome_branded) {
  # Google-specific Legacy GUIDs that Omaha 4 supports.
  updater_legacy_idl_guids = [
    "PLACEHOLDER-GUID-d789bec4-f247-42df-ad56-fa5775b61848=cabd1cfd-2c5f-46a1-8105-564b3a6563ec",  # UpdaterLegacyLib
    "PLACEHOLDER-GUID-03f6780a-31ee-45f0-b55e-f0d465d8bb3a=6d1e4dbb-1821-4505-be78-c9489ce711ce",  # GoogleUpdate3WebUserClass
    "PLACEHOLDER-GUID-f4bb2727-3a47-479c-a0b8-7c3ee73cddf7=88f09f15-24eb-4ca1-8659-720e291636d3",  # GoogleUpdate3WebSystemClass
    "PLACEHOLDER-GUID-568a8900-e3db-4fa0-b320-5ead284038c6=28d07c9b-1175-4ba4-a005-9440b69b7a41",  # GoogleUpdate3WebServiceClass
    "PLACEHOLDER-GUID-d48c091a-dea9-41e4-9d36-5ad849a466c5=b9410c8d-6c42-461f-95c2-0c920e8c63db",  # PolicyStatusUserClass
    "PLACEHOLDER-GUID-58712509-616f-40c5-9682-427c15432c4c=3b3ce4f3-17fb-4e7e-9ee9-87d2758cd885",  # PolicyStatusSystemClass
    "PLACEHOLDER-GUID-163b3ca0-8d0b-47ca-817d-41c638fa9260=30ec2bb6-1281-47b9-abd6-52cec03baf8e",  # ProcessLauncherClass
    "PLACEHOLDER-GUID-87a931b9-770b-4403-a1eb-a8e8f8cb1892=6db98774-99ec-4808-b392-8f60f1096fbc",  # ICurrentState
    "PLACEHOLDER-GUID-0b0d10c8-d604-406d-96f7-21fe78212c50=2188ef30-278b-4617-8039-4df5d621ed47",  # IGoogleUpdate3Web
    "PLACEHOLDER-GUID-3c027e5a-adc6-4d87-93b8-36596b50a845=af6f136d-5973-4de4-a6e2-697d5b33cd17",  # IAppBundleWeb
    "PLACEHOLDER-GUID-fc0f00b9-36a6-47c1-aa51-a3dcbab09c01=8f879527-a89f-40e4-bc84-f1ea57ec0884",  # IAppWeb
    "PLACEHOLDER-GUID-87a649eb-2cc7-46c3-82ea-b674f568b2a4=56551759-8200-4a85-a8e0-ace39e9ccf14",  # IAppCommandWeb
    "PLACEHOLDER-GUID-973209b4-6d14-4865-9716-905aee40ebe4=c4de041b-c1a6-49e3-b822-4ac964dc780f",  # IPolicyStatus
    "PLACEHOLDER-GUID-b591952e-3ef9-4d50-bf39-ef3e79960430=152477dd-1062-4e57-ba29-271565e2a2bf",  # IPolicyStatus2
    "PLACEHOLDER-GUID-778267d6-1b65-4170-ae79-9056dd3a013b=ed8d273d-59db-4969-a621-252115a2cf8f",  # IPolicyStatus3
    "PLACEHOLDER-GUID-b5f81657-0809-4dbf-89ba-1e5fb6f28989=d93caa32-843f-4b1f-b305-ba655227a8f7",  # IPolicyStatusValue
    "PLACEHOLDER-GUID-97addc89-d368-4d88-8f01-cb69c402fbaf=dcaa7bb1-fff1-4684-9227-8baa3a131f4d",  # IProcessLauncher
    "PLACEHOLDER-GUID-76868039-4be2-40bf-bb96-a7644861eeff=7902c919-c2a4-4e7c-aabc-fcf2c9af3c74",  # IProcessLauncher2s
  ]
} else {
  updater_legacy_idl_guids = [
    "PLACEHOLDER-GUID-d789bec4-f247-42df-ad56-fa5775b61848=cabd1cfd-2c5f-46a1-8105-564b3a6563ec",  # UpdaterLegacyLib
    "PLACEHOLDER-GUID-03f6780a-31ee-45f0-b55e-f0d465d8bb3a=6d1e4dbb-1821-4505-be78-c9489ce711ce",  # GoogleUpdate3WebUserClass
    "PLACEHOLDER-GUID-f4bb2727-3a47-479c-a0b8-7c3ee73cddf7=88f09f15-24eb-4ca1-8659-720e291636d3",  # GoogleUpdate3WebSystemClass
    "PLACEHOLDER-GUID-568a8900-e3db-4fa0-b320-5ead284038c6=28d07c9b-1175-4ba4-a005-9440b69b7a41",  # GoogleUpdate3WebServiceClass
    "PLACEHOLDER-GUID-d48c091a-dea9-41e4-9d36-5ad849a466c5=b9410c8d-6c42-461f-95c2-0c920e8c63db",  # PolicyStatusUserClass
    "PLACEHOLDER-GUID-58712509-616f-40c5-9682-427c15432c4c=3b3ce4f3-17fb-4e7e-9ee9-87d2758cd885",  # PolicyStatusSystemClass
    "PLACEHOLDER-GUID-163b3ca0-8d0b-47ca-817d-41c638fa9260=30ec2bb6-1281-47b9-abd6-52cec03baf8e",  # ProcessLauncherClass
    "PLACEHOLDER-GUID-87a931b9-770b-4403-a1eb-a8e8f8cb1892=6db98774-99ec-4808-b392-8f60f1096fbc",  # ICurrentState
    "PLACEHOLDER-GUID-0b0d10c8-d604-406d-96f7-21fe78212c50=2188ef30-278b-4617-8039-4df5d621ed47",  # IGoogleUpdate3Web
    "PLACEHOLDER-GUID-3c027e5a-adc6-4d87-93b8-36596b50a845=af6f136d-5973-4de4-a6e2-697d5b33cd17",  # IAppBundleWeb
    "PLACEHOLDER-GUID-fc0f00b9-36a6-47c1-aa51-a3dcbab09c01=8f879527-a89f-40e4-bc84-f1ea57ec0884",  # IAppWeb
    "PLACEHOLDER-GUID-87a649eb-2cc7-46c3-82ea-b674f568b2a4=56551759-8200-4a85-a8e0-ace39e9ccf14",  # IAppCommandWeb
    "PLACEHOLDER-GUID-973209b4-6d14-4865-9716-905aee40ebe4=c4de041b-c1a6-49e3-b822-4ac964dc780f",  # IPolicyStatus
    "PLACEHOLDER-GUID-b591952e-3ef9-4d50-bf39-ef3e79960430=152477dd-1062-4e57-ba29-271565e2a2bf",  # IPolicyStatus2
    "PLACEHOLDER-GUID-778267d6-1b65-4170-ae79-9056dd3a013b=ed8d273d-59db-4969-a621-252115a2cf8f",  # IPolicyStatus3
    "PLACEHOLDER-GUID-b5f81657-0809-4dbf-89ba-1e5fb6f28989=d93caa32-843f-4b1f-b305-ba655227a8f7",  # IPolicyStatusValue
    "PLACEHOLDER-GUID-97addc89-d368-4d88-8f01-cb69c402fbaf=dcaa7bb1-fff1-4684-9227-8baa3a131f4d",  # IProcessLauncher
    "PLACEHOLDER-GUID-76868039-4be2-40bf-bb96-a7644861eeff=7902c919-c2a4-4e7c-aabc-fcf2c9af3c74",  # IProcessLauncher2
  ]
}
updater_legacy_idl_guids = string_join(",", updater_legacy_idl_guids)

midl("updater_legacy_idl_idl") {
  dynamic_guids = "ignore_proxy_stub," + updater_legacy_idl_guids

  sources = [ "updater_legacy_idl.template" ]
  writes_tlb = true
}

# The COM server needs to work with Windows 7, so explicitly setting the defines
# to reflect this. Otherwise, WRL uses APIs that are only available in later
# Windows versions.
config("winver") {
  defines = [
    "NTDDI_VERSION=NTDDI_WIN7",

    # Hardcoding version 0x0601, since _WIN32_WINNT_WIN7 may not be defined.
    "_WIN32_WINNT=0x0601",
    "WINVER=0x0601",
  ]
}
