# Copyright 2020 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/chrome_build.gni")

  browser_name = "Tomi"
  browser_product_name = "Tomi"
  crash_product_name = "TomiUpdater"
  crash_upload_url = "https://clients2.google.com/cr/staging_report"
  help_center_url = "http://support.google.com/installer/"
  app_logo_url = "https://dl.google.com/update2/installers/icons/"
  keystone_app_name = "TomiSoftwareUpdate"
  keystone_bundle_identifier = "org.chromium.Keystone"
  mac_browser_bundle_identifier = "com.Tomi.Tomi"
  mac_updater_bundle_identifier = "com.Tomi.TomiUpdater"
  privileged_helper_bundle_name = "TomiUpdaterPrivilegedHelper"
  privileged_helper_name = "com.Tomi.Tomi.UpdaterPrivilegedHelper"
  updater_company_full_name = "Tomi Authors"
  updater_company_short_name = "Tomi"
  updater_company_short_name_uppercase = "TOMI"
  updater_copyright =
      "Copyright 2024 The Tomi Authors. All rights reserved."
  updater_product_full_name = "TomiUpdater"
  mac_team_identifier = "6FTDXZ346N"
  #updater_appid = "{a04d6beb-0b7f-4e98-ae2f-b52c5c591675}"
  #qualification_appid = "{6f0f9a34-a0ab-4a75-a0eb-6eab78d0dc4b}"
  updater_appid = "{a04d6beb-0b7f-4e98-ae2f-b52c5c591676}"
  qualification_appid = "{6f0f9a34-a0ab-4a75-a0eb-6eab78d0dc4b}"
  legacy_service_name_prefix = "cupdate"
  prefs_access_mutex = "{764e0958-587b-41aa-a3af-aff426181971}"
  setup_mutex_prefix = "{6ddbf5d4-a274-49b4-bd32-31dc782cc911}"
  grdfile_name = "chromium_strings"
  extra_args_is_chrome_branded = "IS_CHROME_BRANDED=False"

  UpdaterLegacyLibGUID = "cabd1cfd-2c5f-46a1-8105-564b3a6563ec"
  GoogleUpdate3WebUserClassGUID = "6d1e4dbb-1821-4505-be78-c9489ce711ce"
  GoogleUpdate3WebSystemClassGUID = "88f09f15-24eb-4ca1-8659-720e291636d3"
  GoogleUpdate3WebServiceClassGUID = "28d07c9b-1175-4ba4-a005-9440b69b7a41"
  PolicyStatusUserClassGUID = "b9410c8d-6c42-461f-95c2-0c920e8c63db"
  PolicyStatusSystemClassGUID = "3b3ce4f3-17fb-4e7e-9ee9-87d2758cd885"
  ProcessLauncherClassGUID = "30ec2bb6-1281-47b9-abd6-52cec03baf8e"

  IAppVersionWebGUID = "02eee879-e42b-46e9-bbb4-e92cbe5b6f40"
  IAppVersionWebUserGUID = "788DEB11-4843-4760-9A28-D61DCBD9C299"
  IAppVersionWebSystemGUID = "F258BE54-7C5F-44A0-AAE0-730620A31D23"

  ICurrentStateGUID = "6db98774-99ec-4808-b392-8f60f1096fbc"
  ICurrentStateUserGUID = "67560A6B-7409-4DF0-BB6E-F51BAA7BB605"
  ICurrentStateSystemGUID = "E9CD91E3-A00C-4B9E-BD63-7F34EB815D98"

  IGoogleUpdate3WebGUID = "2188ef30-278b-4617-8039-4df5d621ed47"
  IGoogleUpdate3WebUserGUID = "D866C8ED-7F89-4A87-9760-CF24C770A667"
  IGoogleUpdate3WebSystemGUID = "5F793925-C903-4E92-9AE3-77CA5EAB1716"

  IAppBundleWebGUID = "af6f136d-5973-4de4-a6e2-697d5b33cd17"
  IAppBundleWebUserGUID = "6577ADDF-BE03-425A-A372-575A91EBACD8"
  IAppBundleWebSystemGUID = "C4622B28-A747-44C7-96AF-319BE5C3B261"

  IAppWebGUID = "8f879527-a89f-40e4-bc84-f1ea57ec0884"
  IAppWebUserGUID = "FD46087A-75DA-47E8-B2C4-F25E523D0A5E"
  IAppWebSystemGUID = "D576ED7F-31DA-4EE1-98CE-1F882FB3047A"

  IAppCommandWebGUID = "56551759-8200-4a85-a8e0-ace39e9ccf14"
  IAppCommandWebUserGUID = "154F5BCB-F504-4C32-89B3-91E30C5AE9B9"
  IAppCommandWebSystemGUID = "1F1289FD-DD10-4579-81F6-1C59AAF2E1A9"

  IPolicyStatusGUID = "c4de041b-c1a6-49e3-b822-4ac964dc780f"
  IPolicyStatusUserGUID = "3D7EFA34-1680-4643-9D06-CAD08B3CAA55"
  IPolicyStatusSystemGUID = "B685B009-DBC4-4F24-9542-A162C3793E77"

  IPolicyStatus2GUID = "152477dd-1062-4e57-ba29-271565e2a2bf"
  IPolicyStatus2UserGUID = "5801641E-17F0-47CC-8FF6-DCF5857B2A9F"
  IPolicyStatus2SystemGUID = "513BC7DA-6B8D-45F7-90A0-2E9F66CEF962"

  IPolicyStatus3GUID = "ed8d273d-59db-4969-a621-252115a2cf8f"
  IPolicyStatus3UserGUID = "38E9E61D-A104-46E2-9645-C3E7EFF9FD7C"
  IPolicyStatus3SystemGUID = "F4334319-8210-469B-8262-DD03623FEB5B"

  IPolicyStatusValueGUID = "d93caa32-843f-4b1f-b305-ba655227a8f7"
  IPolicyStatusValueUserGUID = "2EFD593A-304B-4544-AC39-A02D9105FB8C"
  IPolicyStatusValueSystemGUID = "4DC034A8-4BFC-4D43-9250-914163356BB0"

  IProcessLauncherGUID = "dcaa7bb1-fff1-4684-9227-8baa3a131f4d"
  IProcessLauncherSystemGUID = "F4FE76BC-62B9-49FC-972F-C81FC3A926DB"

  IProcessLauncher2GUID = "7902c919-c2a4-4e7c-aabc-fcf2c9af3c74"
  IProcessLauncher2SystemGUID = "6430040A-5EBD-4E63-A56F-C71D5990F827"

  if (is_mac) {
    legacy_google_update_appid = keystone_bundle_identifier
  } else {
    legacy_google_update_appid = "{430FD4D0-B729-4F61-AA34-91526481799D}"
  }

# Chrome and Chromium share the same endpoints for now.
update_check_url = "http://omaha.tomi.com:8080/update" 
device_management_server_url = "http://omaha.tomi.com:8080"
