# Copyright 2020 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/chrome_build.gni")

  browser_name = "Tomi"
  browser_product_name = "Tomi"
  crash_product_name = "TomiUpdater"
  crash_upload_url = "https://clients2.google.com/cr/staging_report"
  help_center_url = "http://support.google.com/installer/"
  app_logo_url = "https://dl.google.com/update2/installers/icons/"
  keystone_app_name = "TomiSoftwareUpdate"
  keystone_bundle_identifier = "org.chromium.Keystone"
  mac_browser_bundle_identifier = "com.Tomi.Tomi"
  mac_updater_bundle_identifier = "com.Tomi.TomiUpdater"
  privileged_helper_bundle_name = "TomiUpdaterPrivilegedHelper"
  privileged_helper_name = "com.Tomi.Tomi.UpdaterPrivilegedHelper"
  updater_company_full_name = "Tomi Authors"
  updater_company_short_name = "Tomi"
  updater_company_short_name_uppercase = "TOMI"
  updater_copyright =
      "Copyright 2024 The Tomi Authors. All rights reserved."
  updater_product_full_name = "TomiUpdater"
  mac_team_identifier = "6FTDXZ346N"
  #updater_appid = "{a04d6beb-0b7f-4e98-ae2f-b52c5c591675}"
  #qualification_appid = "{4890207c-a4a1-4e6e-8be8-2e28c0de7290}"
  updater_appid = "{18217356-b676-4b3b-93ba-641fabf142c7}"
  qualification_appid = "{4890207c-a4a1-4e6e-8be8-2e28c0de7290}"
  legacy_service_name_prefix = "cupdate"
  prefs_access_mutex = "{c65f9766-4ef0-47cd-8c61-6cd09905dc5b}"
  setup_mutex_prefix = "{1e56e1f2-0821-4e4e-8c2f-4ac7d8d181a9}"
  grdfile_name = "chromium_strings"
  extra_args_is_chrome_branded = "IS_CHROME_BRANDED=False"

  UpdaterLegacyLibGUID = "8b10c18e-130b-49ec-a615-6dae002ef7fa"
  GoogleUpdate3WebUserClassGUID = "e23abf2b-e374-410d-a063-b7ea81f9efbd"
  GoogleUpdate3WebSystemClassGUID = "67f89642-f891-4e14-b164-874dc5917636"
  GoogleUpdate3WebServiceClassGUID = "12e7e3e7-87d4-4f18-a55d-cc5572ff697c"
  PolicyStatusUserClassGUID = "2e589042-b81a-4177-975a-95a7de516538"
  PolicyStatusSystemClassGUID = "1492f8f7-619e-4596-8712-f1977ff8322b"
  ProcessLauncherClassGUID = "c02702a2-26d6-4cb8-919c-ff4c54c8b514"

  IAppVersionWebGUID = "389906fe-1dcc-42b4-a2fb-298de1c26cde"
  IAppVersionWebUserGUID = "7f7c79e6-960c-4df9-bfdc-75efb749760b"
  IAppVersionWebSystemGUID = "79da3599-459c-4b38-9c85-a637a825c8f0"

  ICurrentStateGUID = "3751f241-2040-44ad-9a43-73511b43a5d9"
  ICurrentStateUserGUID = "715069eb-b82f-4507-8bb8-2325f0a4e39d"
  ICurrentStateSystemGUID = "275835c6-9834-42cc-92f3-d019d6d89659"

  IGoogleUpdate3WebGUID = "b8b6e59a-17a2-4c7d-bf40-2e04443684b6"
  IGoogleUpdate3WebUserGUID = "25438666-d4ad-4bde-a17d-9b1faf5801fc"
  IGoogleUpdate3WebSystemGUID = "9c3343f9-7631-4a39-9ebc-f894d5b31199"

  IAppBundleWebGUID = "a52e87d9-ffed-4f3c-b845-a4bc785a4b5a"
  IAppBundleWebUserGUID = "2c184f5f-2153-45a6-b1c7-e1a127f68461"
  IAppBundleWebSystemGUID = "5e0ae6f5-47c2-49a4-9b18-75177269d3f3"

  IAppWebGUID = "f4133240-83f3-42d1-8155-5ace2956d772"
  IAppWebUserGUID = "FD46087A-75DA-47E8-B2C4-F25E523D0A5E"
  IAppWebSystemGUID = "D576ED7F-31DA-4EE1-98CE-1F882FB3047A"

  IAppCommandWebGUID = "4de5a51d-a2c8-4328-818b-e90133392316"
  IAppCommandWebUserGUID = "154F5BCB-F504-4C32-89B3-91E30C5AE9B9"
  IAppCommandWebSystemGUID = "1F1289FD-DD10-4579-81F6-1C59AAF2E1A9"

  IPolicyStatusGUID = "8762545d-5c42-44ee-a9a2-c5ca5e7ef463"
  IPolicyStatusUserGUID = "3D7EFA34-1680-4643-9D06-CAD08B3CAA55"
  IPolicyStatusSystemGUID = "B685B009-DBC4-4F24-9542-A162C3793E77"

  IPolicyStatus2GUID = "bea5ab38-aee5-4708-bf1e-9a338bb706ca"
  IPolicyStatus2UserGUID = "5801641E-17F0-47CC-8FF6-DCF5857B2A9F"
  IPolicyStatus2SystemGUID = "513BC7DA-6B8D-45F7-90A0-2E9F66CEF962"

  IPolicyStatus3GUID = "91bb172f-b84f-4662-9948-5dce65a4423a"
  IPolicyStatus3UserGUID = "38E9E61D-A104-46E2-9645-C3E7EFF9FD7C"
  IPolicyStatus3SystemGUID = "F4334319-8210-469B-8262-DD03623FEB5B"

  IPolicyStatusValueGUID = "f9e2de38-a2c4-4a00-b072-983f1d385494"
  IPolicyStatusValueUserGUID = "2EFD593A-304B-4544-AC39-A02D9105FB8C"
  IPolicyStatusValueSystemGUID = "4DC034A8-4BFC-4D43-9250-914163356BB0"

  IProcessLauncherGUID = "5d46cda8-d57d-4d56-8218-dfff01d42fe8"
  IProcessLauncherSystemGUID = "24c704b7-fd91-4e4d-b7ba-16de1d7e0258"

  IProcessLauncher2GUID = "546c5da1-e0d0-4e42-8394-e52113cce35c"
  IProcessLauncher2SystemGUID = "fc15bd31-65f2-4ff3-b61f-ee026819d8ef"

  if (is_mac) {
    legacy_google_update_appid = keystone_bundle_identifier
  } else {
    legacy_google_update_appid = "{e249a987-9d3b-42a1-bfd7-731d76101da7}"
  }

# Chrome and Chromium share the same endpoints for now.
update_check_url = "http://omaha.tomi.com:8080/update" 
device_management_server_url = "http://omaha.tomi.com:8080"
